version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    logging:
      driver:"json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
      ExtrenalEventBaseUrl: http://localhost:6180
    ports:
      - "6180:80"
    container_name: eventapi2
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventfinder2
    logging:
      driver:"json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.3.104:6170
      CallBackUrl: http://localhost:5207
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_FFHyJN9riognYFkDbdHYltci
      StripePrivateKey: sk_test_gqNNPG5zWMYlBZbM5tXldLya
    ports:
      - "5207:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart
      - order

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5207
    ports:
      - "6170:80"
    container_name: tokenserviceapi2
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.22:6170
      ConnectionString: basket.data
    ports:
      - "6066:80"
    container_name: cartapi2
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq
  
  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.22:6070
      SQLSERVER_HOST: mssqlserver
      SA_PASSWORD: EventApi(!)
      DATABASE: OrdersDb
    ports:
      - "6175:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: eventsqlserver
    ports:
      - "1445:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6078:6379"  
    networks:
      - backend 


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
      - "5674:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 